### ISSUE TITLE
Set this repo's default branch to 'development'

### ISSUE THREAD

**Issue by nodanaonlyzuul** [NYPL/cancel-request-result-consumer#5]
How do folks feel about changing this [git repo's default branch](https://help.github.com/articles/setting-the-default-branch/) to `development`.  

It'll be nice and all PRs will automatically filed against `development`. 
(default is `master` and this repo considers `master` as stable/production)

**Comment by ktp242** [comment]
The repo used to only have one branch which is `master`, so I guess that's why its default is `master`. For adding QA tier to this application, I added `qa` and `development` branches. Based on this, I think it is right to change the default branch to `development`. I can go change it if everyone's agree with it.

**Comment by nonword** [comment]
Yes. I've been trying to remember to do that. I think the default repo should match the repo we tell people to cut feature branches from.

**Comment by nodanaonlyzuul** [comment]
Cool. I'm going to close this ticket and do that.
